- name: Render MetalLB IPAddressPool into a real YAML
  template:
    src: "{{ playbook_dir }}/templates/metallb/ipaddresspool.yaml.j2"
    dest: "/tmp/ipaddresspool.yaml"

- name: Apply MetalLB IPAddressPool
  kubernetes.core.k8s:
    state: present
    src: "/tmp/ipaddresspool.yaml"