---

# RKE2 installation method (do not change this option)
rke2_method: tar
rke2_service_name: "rke2-{{ rke2_type }}.service"
rke2_restart_needed: false
# Optional changes
rke2_download_kubeconf: true
rke2_download_kubeconf_path: ~/.kube
rke2_download_kubeconf_file_name: config
rke2_ingress_nginx_values:
  controller:
    hostNetwork: true
    hostPort:
      enabled: true
    ingressClassResource:
      default: true
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/hostname: mn0
    service:
      enabled: true
      external:
        enabled: true
      type: LoadBalancer
      loadBalancerIP: "{{ ingress_ip }}"
      externalTrafficPolicy: "Local"
    admissionWebhooks:
      enabled: false
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
  defaultBackend:
    enabled: true
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      kubernetes.io/os: linux
      kubernetes.io/hostname: mn0