all:
  vars:
    control_plane_endpoint: 192.168.3.100
    gateway: 192.168.3.254
metal:
  children:
    masters:
      hosts:
        # mn0: {ansible_host: 192.168.3.110, mac: 'c0:7c:d1:fe:3c:6b', disk: sda, network_interface: eno1}
        mn0: {ansible_host: 192.168.3.110, mac: '48:21:0b:36:cd:c8', disk: sda, network_interface: eth0}
        # mn2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1}
    # workers:
    #   hosts:
    #     metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
