all:
  vars:
    host_address: 192.168.3.10
    gateway: 192.168.3.254
    host_network: 192.168.3.0/24
    broadcast: 192.168.3.255
    netmask: 255.255.255.0
    interface: "eth0"
metal:
  children:
    masters:
      hosts:
        # mn0: {ansible_host: 192.168.3.110, mac: 'c0:7c:d1:fe:3c:6b', disk: sda, network_interface: eno1}
        mn0: {ansible_host: 192.168.3.110, mac: '48:21:0b:36:cd:c8', disk: sdb, network_interface: eth0}
        # mn2: {ansible_host: 192.168.1.112, mac: '00:23:24:e7:04:60', disk: sda, network_interface: eno1}
    # workers:
    #   hosts:
    #     metal3: {ansible_host: 192.168.1.113, mac: '00:23:24:d1:f4:d6', disk: sda, network_interface: eno1}
