- name: Instruct Ansible that default IPv4 is on the LAN link
  set_fact:
    ansible_default_ipv4:
      address: "{{ host_address }}"
      network: "{{ host_network | ansible.netcommon.ipmath(1) }}"
      netmask: "{{ netmask }}"
      gateway: "{{ ip_forwarding | bool | ternary(host_address, static_gateway) }}"
      interface: "{{ interface }}"
      broadcast: "{{ broadcast }}"

- name: Get Docker info
  docker_host_info: {}
  register: docker_info_result

- name: Ensure Docker is running on a supported operating system
  fail:
    msg: Docker host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac or Windows (you can use a Linux VM with bridged networking instead)
  when:
    - docker_info_result.host_info.OperatingSystem == "Docker Desktop"

- name: Download boot image
  ansible.builtin.get_url:
    url: "{{ iso_url }}"
    dest: "{{ role_path }}/files/data/iso/{{ iso_url | basename }}"
    checksum: "{{ iso_checksum }}"
    mode: 0644
  register: iso

# Verify previous .treeinfo file does not exist
- name: Extract boot image
  ansible.builtin.command:
    cmd: "xorriso -osirrox on -indev {{ iso.dest }} -extract / {{ role_path }}/files/data/os"
    creates: "{{ role_path }}/files/data/os/.treeinfo"

# - name: Extract only the x86_64-efi helper directory from the ISO
#   ansible.builtin.command:
#     cmd: >
#       xorriso -osirrox on -indev {{ iso.dest }} -extract /EFI/BOOT/x86_64-efi {{ role_path }}/files/data/os/EFI/BOOT
#   args:
#     creates: "{{ role_path }}/files/data/os/EFI/BOOT/x86_64-efi/command.lst"

- name: Find all directories under {{ role_path }}/files/
  ansible.builtin.find:
    paths: "{{ role_path }}/files/"
    file_type: directory
    recurse: true
  register: os_dirs

- name: Set directories to 0755
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0755"
  loop: "{{ os_dirs.files }}"

- name: Find all files under {{ role_path }}/files/
  ansible.builtin.find:
    paths: "{{ role_path }}/files/"
    file_type: file
    recurse: true
  register: os_files

- name: Set files to 0644
  ansible.builtin.file:
    path: "{{ item.path }}"
    mode: "0644"
  loop: "{{ os_files.files }}"

- name: Generate dnsmasq config
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ role_path }}/files/data/pxe-config/dnsmasq.conf"
    mode: 0644

- name: Generate GRUB config
  ansible.builtin.template:
    src: grub.cfg.j2
    dest: "{{ role_path }}/files/data/pxe-config/grub.cfg"
    mode: 0644

- name: Generate init config for each machine
  ansible.builtin.template:
    src: kickstart.ks.j2
    dest: "{{ role_path }}/files/data/init-config/{{ hostvars[item]['mac'] }}.ks"
    mode: 0644
  loop: "{{ groups['metal'] }}"

- name: Start the ephemeral PXE server
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    state: present
    build: always

- name: Ensure ip forwarding is enabled
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Install iptables‑persistent (Debian/Ubuntu)
  ansible.builtin.package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == 'Debian'

- name: Install iptables services (RHEL/CentOS)
  ansible.builtin.package:
    name: iptables-services
    state: present
  when: ansible_os_family == 'RedHat'

- name: Set up NAT masquerade rule
  ansible.builtin.command: >
    iptables -t nat -C POSTROUTING -o {{ internet_if }} -j MASQUERADE
  register: nat_rule_check
  failed_when: nat_rule_check.rc not in [0,1]
  changed_when: nat_rule_check.rc == 1

- name: Add NAT masquerade if missing
  ansible.builtin.command: >
    iptables -t nat -A POSTROUTING -o {{ internet_if }} -j MASQUERADE
  when: nat_rule_check.rc == 1

- name: Allow forwarding from LAN to WAN
  ansible.builtin.command: >
    iptables -C FORWARD -i {{ cluster_if }} -o {{ internet_if }} -m state --state RELATED,ESTABLISHED -j ACCEPT
  register: fwd_est_check
  failed_when: fwd_est_check.rc not in [0,1]
  changed_when: fwd_est_check.rc == 1

- name: Add FORWARD rule for established connections
  ansible.builtin.command: >
    iptables -A FORWARD -i {{ cluster_if }} -o {{ internet_if }} -m state --state RELATED,ESTABLISHED -j ACCEPT
  when: fwd_est_check.rc == 1

- name: Allow forwarding from WAN to LAN
  ansible.builtin.command: >
    iptables -C FORWARD -i {{ internet_if }} -o {{ cluster_if }} -j ACCEPT
  register: fwd_new_check
  failed_when: fwd_new_check.rc not in [0,1]
  changed_when: fwd_new_check.rc == 1

- name: Add FORWARD rule for new connections
  ansible.builtin.command: >
    iptables -A FORWARD -i {{ internet_if }} -o {{ cluster_if }} -j ACCEPT
  when: fwd_new_check.rc == 1

- name: Save iptables rules (Debian/Ubuntu)
  ansible.builtin.command: >
    netfilter-persistent save
  when: ansible_os_family == 'Debian'

- name: Save iptables rules (RHEL/CentOS)
  ansible.builtin.command: >
    service iptables save
  when: ansible_os_family == 'RedHat'

- name: Ensure iptables service is enabled and running (RHEL)
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: yes
  when: ansible_os_family == 'RedHat'