---
- name: Include prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yaml

- name: Include pre-configurations only if file exists
  ansible.builtin.include_tasks:
    file: "{{ file }}"
  loop_control:
    loop_var: file
  with_first_found:
    - files:
      - "../tasks/infra/pre/{{ item.name }}.yaml"
      skip: true

- name: Install release ({{ item.name }})
  kubernetes.core.helm:
    name: "{{ item.name }}"
    chart_ref: "{{ item.chart_ref }}"
    chart_version: "{{ item.version }}"
    release_namespace: "{{ item.namespace }}"
    create_namespace: false
    chart_repo_url: "{{ item.repo_url }}"
    values: "{{ item.release_values | default({}) }}"
    # {% if item.release_values | length > 0 %}
    #       {{ item.release_values | to_nice_yaml(indent=2) | indent(4) }}
    # {% endif %}
    wait: true

- name: Include post-configurations only if file exists
  ansible.builtin.include_tasks:
    file: "{{ file }}"
  loop_control:
    loop_var: file
  with_first_found:
    - files:
      - "../tasks/infra/post/{{ item.name }}.yaml"
      skip: true