---
- name: Ensure namespace {{ item.namespace }} exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.namespace }}"
  delegate_to: 127.0.0.1
  run_once: true

- name: Register if Helm repository is installed
  ansible.builtin.command: helm search repo {{ item.name }} -n {{ item.namespace }}
  register: repo_installed
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true

- name: Add Helm repository
  ansible.builtin.command: helm repo add {{ item.repo_name }} {{ item.repo_url }}
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true
  when: "repo_installed.stdout.find(item.name) == -1"

- name: Update local Helm chart repository cache
  ansible.builtin.command: helm repo update -n {{ item.namespace }}
  changed_when: false
  delegate_to: 127.0.0.1
  run_once: true