ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
dns_server: "8.8.8.8"
ip_forwarding: true     # set to true if internet-forwarding is required from the DA
static_gateway: "192.168.3.254"