# Metal
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ssh_public_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
dns_server: "8.8.8.8"
ip_forwarding: true                 # set to true if internet-forwarding is required from the DA
static_gateway: "192.168.3.254"     #  used if internet-forwarding is not required from the DA

# RKE2
rke2_version: v1.33.1+rke2r1
rke2_cni: calico
rke2_cis_profile: "cis"
rke2_download_kubeconf: true
rke2_download_kubeconf_path: ~/.kube
rke2_download_kubeconf_file_name: kubeconfig.yaml