- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: true
  when: ip_forwarding | bool

- name: Masquerade LAN → WAN
  iptables:
    table: nat
    chain: POSTROUTING
    out_interface: "{{ internet_interface }}"
    jump: MASQUERADE
    state: present

- name: Allow forwarding LAN → WAN
  iptables:
    # table: filter
    chain: FORWARD
    out_interface: "{{ internet_interface }}"
    source: "{{ host_network }}"
    jump: ACCEPT
    state: present

- name: Input rules for LAN → WAN
  iptables:
    # table: filter
    chain: INPUT
    source: "{{ host_network }}"
    jump: ACCEPT
    state: present

- name: Ensure Docker‑USER chain does not block us
  iptables:
    table: filter
    chain: DOCKER-USER
    jump: ACCEPT
    state: present

- name: Save iptables (RHEL/Fedora/CentOS)
  command: service iptables save
  when: ansible_os_family in ['RedHat','Fedora']